Exercise 2
Jezik/QA-Automation-Course pull request #3
Opened 2023-05-21 17:48 UTC by Jezik

First commit is a simple addition of assert statement to verify if the login was successful. With one more selector and helpeer function, that I found to be useful. 

The second commit is a test for adding the item to a cart with selectors and helpers and new files. 

Also, I've added pytest import in order to run tests with a simple `pytest` command. 
I completely don't like the amount of duplicate code, but I wasn't able to get rid of it without using classes and maybe Pytest fixtures. I need to dive into it if you'll find it necessary on this stage.

2023-05-24 13:53 UTC, WaclawZurko commented on helpers/helpers.py
> +def check_if_element_exists(driver, selector):
GJ, nice one

2023-05-24 13:54 UTC, WaclawZurko commented on tests/shop_page_test.py
> +time.sleep(3)
We will learn how to omit "hard sleeps" but for now its fine

2023-05-24 13:55 UTC, WaclawZurko commented on tests/shop_page_test.py
> +def test_item_added_to_cart():
Its just a declaration of function - we need also "call" this function

2023-05-24 13:59 UTC, WaclawZurko requested changes
Hey, please:
+ move function "test_item_added_to_cart" to pages/shop_page.py
+ call that function in "tests/shop_page_test.py"

2023-05-27 13:49 UTC, Jezik commented
First commit - move declaration of *_test.py functions from _test.py files. Add .vscode.settings.json file in order VSCode can resolve the paths easier and highlight the syntax correctly. 

Second commit - add headless mode and move options and driver initialization into helpers.py

2023-05-30 12:37 UTC, WaclawZurko approved these changes

2023-05-30 12:37 UTC, merged